Violence_Against_Women_fsftn_2014/config/routes.rb
Rails.application.routes.draw do

  resources :blogs

  resources :joins

get "home" => "home#home"

get "about" => "about#about"

end

Violence_Against_Women_fsftn_2014/app/models/blog.rb
class Blog < ActiveRecord::Base
end

Violence_Against_Women_fsftn_2014/app/models/join.rb
class Join < ActiveRecord::Base
end

Violence_Against_Women_fsftn_2014/app/controllers/about_controller.rb
class AboutController < ApplicationController
	def about
	end
end

Violence_Against_Women_fsftn_2014/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Violence_Against_Women_fsftn_2014/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show

    @blogs_all = Blog.all
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :post, :author)
    end
end

Violence_Against_Women_fsftn_2014/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
	end
end

Violence_Against_Women_fsftn_2014/app/controllers/joins_controller.rb
class JoinsController < ApplicationController
  before_action :set_join, only: [:show, :edit, :update, :destroy]

  # GET /joins
  # GET /joins.json
  def index
    #@joins = Join.all
    @join = Join.new
  end

  # GET /joins/1
  # GET /joins/1.json
  def show
  end

  # GET /joins/new
  def new
    @join = Join.new
  end

  # GET /joins/1/edit
  def edit
  end

  # POST /joins
  # POST /joins.json
  def create
    @join = Join.new(join_params)

    respond_to do |format|
      if @join.save
        format.html { redirect_to @join, notice: 'Thanks for joining' }
        format.json { '' }
      else
        format.html { render :new }
        format.json { render json: @join.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joins/1
  # PATCH/PUT /joins/1.json
  def update
    respond_to do |format|
      if @join.update(join_params)
        format.html { redirect_to @join, notice: 'Join was successfully updated.' }
        format.json { render :show, status: :ok, location: @join }
      else
        format.html { render :edit }
        format.json { render json: @join.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joins/1
  # DELETE /joins/1.json
  def destroy
    @join.destroy
    respond_to do |format|
      format.html { redirect_to joins_url, notice: 'Join was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_join
      @join = Join.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def join_params
      params.require(:join).permit(:name, :email, :phone)
    end
end

Violence_Against_Women_fsftn_2014/app/helpers/about_helper.rb
module AboutHelper
end

Violence_Against_Women_fsftn_2014/app/helpers/application_helper.rb
module ApplicationHelper
end

Violence_Against_Women_fsftn_2014/app/helpers/blogs_helper.rb
module BlogsHelper
end

Violence_Against_Women_fsftn_2014/app/helpers/home_helper.rb
module HomeHelper
end

Violence_Against_Women_fsftn_2014/app/helpers/joins_helper.rb
module JoinsHelper
end

Violence_Against_Women_fsftn_2014/app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_area :post %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Violence_Against_Women_fsftn_2014/app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

Violence_Against_Women_fsftn_2014/app/views/blogs/index.html.erb
<div class="headerWrapper">
  <h1 id="title">Stop voilence against Women</h1>
  <ul class="nav">
    <li><%= link_to 'Home', 'home' %></li>
    <li><%= link_to 'About', 'about' %></li>
    <li><%= link_to 'Blog', 'blogs' %></li>
    <li><%= link_to 'Join us', 'joins' %></li>
  </ul>
</div>
<div class="blogWrapper">
  <div id="bloglist">
      <% @blogs.each do |blog| %>
        <div class="blog">
          <div class="blogTitle">
            <a id="<%= blog.title%>"><%= link_to blog.title, blog %></a>
          </div>
          <div class="blogContent">
            <%= blog.post %>
          </div>
          <div class="blogAuthor">
            <%= blog.author %>
          </div>
        <div class="blogOptions">
          <ul>
            <li><%= link_to 'Edit', edit_blog_path(blog) %></li>
            <li><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </div>
        </div>
        <% end %>
  </div>
    <div class="sideTitle">
      <h3>Titles</h3>
      <ul class="nav siceNav">
        <% @blogs.each do |blog| %>
          <li>
            <a href="#<%= blog.title %>"><%= blog.title %></a>
          </li>
        <% end %>
      </ul>
    </div>
</div>
<div class="newBlog">
  <%= link_to 'New Blog', new_blog_path %>
</div>

Violence_Against_Women_fsftn_2014/app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

Violence_Against_Women_fsftn_2014/app/views/blogs/show.html.erb
<div class="headerWrapper">
  <h1 id="title">Stop voilence against Women</h1>
  <ul class="nav">
    <li><%= link_to 'Home', 'home' %></li>
    <li><%= link_to 'About', 'about' %></li>
    <li><%= link_to 'Blog', 'blogs' %></li>
    <li><%= link_to 'Join us', 'joins' %></li>
  </ul>
</div>
<div class="blogWrapper">
  <div id="bloglist">
        <div class="blog">
          <div class="blogTitle">
			  <%= @blog.title %>
          </div>
          <div class="blogContent" style = "height: auto;">
  <%= @blog.post %>
          </div>
          <div class="blogAuthor">
  <%= @blog.author %>
          </div>
        <div class="blogOptions">
          <ul>
            <li>
				<%= link_to 'Edit', edit_blog_path(@blog) %>
			</li>
			<li>
				<%= link_to 'Back', blogs_path %>
			</li>
          </ul>
        </div>
        </div>
</div>
    <div class="sideTitle">
      <h3>Titles</h3>
      <ul class="nav siceNav">
        <% @blogs_all.each do |blog| %>
          <li><%= link_to blog.title, blog %></li>
        <% end %>
      </ul>
    </div>
</div>

Violence_Against_Women_fsftn_2014/app/views/home/home.html.erb
<div class="headerWrapper">
	<h1 id="title">Stop voilence against Women</h1>
	<ul class="nav">
	    <li><%= link_to 'Home', 'home' %></li>
	    <li><%= link_to 'About', 'about' %></li>
	    <li><%= link_to 'Blog', 'blogs' %></li>
	    <li><%= link_to 'Join us', 'joins' %></li>
	</ul>
</div>
<div id="home_desc">
	<div class="image_text">
		Men are afraid that women will laugh at them. Women are afraid that men will kill them. 
	</div>
</div>

Violence_Against_Women_fsftn_2014/app/views/joins/_form.html.erb
<%= form_for(@join) do |f| %>
  <% if @join.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@join.errors.count, "error") %> prohibited this join from being saved:</h2>

      <ul>
      <% @join.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit 'Join us'%>
  </div>
<% end %>

Violence_Against_Women_fsftn_2014/app/views/joins/edit.html.erb
<h1>Editing join</h1>

<%= render 'form' %>

<%= link_to 'Show', @join %> |
<%= link_to 'Back', joins_path %>

Violence_Against_Women_fsftn_2014/app/views/joins/index.html.erb
<div class="headerWrapper">
  <h1 id="title">Stop voilence against Women</h1>
  <ul class="nav">
    <li><%= link_to 'Home', 'home' %></li>
    <li><%= link_to 'About', 'about' %></li>
    <li><%= link_to 'Blog', 'blogs' %></li>
    <li><%= link_to 'Join us', 'joins' %></li>
  </ul>
</div>

<div id="joinContentWrapper">
  <%= render 'form' %>
</div>

Violence_Against_Women_fsftn_2014/app/views/joins/new.html.erb
<div class="headerWrapper">
	<h1 id="title">Stop voilence agaist Women</h1>
	<ul class="nav">
		<li><%= link_to 'Home', 'home' %></li>
		<li><%= link_to 'About', 'about' %></li>
		<li><%= link_to 'Blog', 'blog' %></li>
		<li><%= link_to 'Join us', 'joins' %></li>
	</ul>
</div>

<div id="joinContentWrapper">
	<%= render 'form' %>
</div>

Violence_Against_Women_fsftn_2014/app/views/joins/show.html.erb
<div class="headerWrapper">
  <h1 id="title">Stop voilence agaist Women</h1>
  <ul class="nav">
    <li><%= link_to 'Home', 'home' %></li>
    <li><%= link_to 'About', 'about' %></li>
    <li><%= link_to 'Blog', 'blogs' %></li>
    <li><%= link_to 'Join us', 'joins' %></li>
  </ul>
</div>

<div id="joinContentWrapper">
	<div id="notice">
		<div id="notice_inner">
			<%= notice %>
	  			<span class="notice_name"><%= @join.name %></span>
  		</div>
	</p>
</div>

Violence_Against_Women_fsftn_2014/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ViolenceAgainstWomenFsftn2014</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>